### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by Avizacherman** [darthhomme/GameGame#1]
Josh,

Great work getting this updated. I like that you added images for the cards, a very nice touch that will make it more enjoyable for the end user. Keep thinking over the black jack problem. Would love to see you implement it eventually as it is a key part of the game. But otherwise I see that you have everything working, as well as a way to track betting. Really good stuff. Keep working at it!

-Avi

**Comment by ajhofferber** [comment]
Hey Josh,

Nice job! The refactoring you did over the last week has helped your game to work much much better! It runs quite smoothly. I really like the ability to bet and keep track of your pot. The use of card images makes it look really nice and makes it more fun as a user to play.

Good start with the markdown! But here is some documentation to look at: https://help.github.com/articles/markdown-basics/  Don't be afraid to use some screenshots, as well as include the technologies you used and some more elaborate user stories. You want this markdown to give those who visit your github a really good sense of the work that you did and what you've accomplished. It's something to be proud of for sure!

Overall, great final product!  Score: 2 (refer to project markdown for scoring rubric)

-Ash
